channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::decoupler-py=1.8.0
- conda-forge::matplotlib=3.10.0
- conda-forge::pandas=2.2.3
- conda-forge::pip=24.3.1
- conda-forge::scanpy=1.10.4
- pip
- pip:
  - omnipath==1.0.8
