name: "decoupler_progeny"

description: |
  The DECOUPLER_PROGENY module applies the PROGENy method using the Decoupler library to infer pathway activity scores from gene expression data. It incorporates multiple statistical methods and visualizations to analyze biological activities within a unified framework, leveraging the PROGENy gene sets specific to the given organism.

keywords:
  - enrichment
  - omics
  - biological activity
  - pathway analysis
  - functional analysis
  - PROGENy

tools:
  - decoupler_progeny:
      description: "Ensemble of methods to infer biological activities from omics data"
      homepage: "https://github.com/saezlab/decoupler-py"
      documentation: "https://decoupler-py.readthedocs.io/en/latest/api.html"
      tool_dev_url: "https://decoupler-py.readthedocs.io"
      doi: "10.1093/bioadv/vbac016"
      licence: ["GPL v3"]
      identifier: biotools:decoupler

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:‘test’, single_end ]
    - mat:
        type: file
        description: |
          Path to the input matrix file (e.g. single-cell gene expression data).
          Should be in HDF5 format (`*.h5ad`).
        pattern: "*.h5ad"
output:
  - dc_estimate:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:‘test’, single_end ]
      - progeny_mlm_estimate_decoupler.tsv:
          type: file
          description: |
            The file containing the estimation results of the enrichment(s)
          pattern: "*progeny_mlm_estimate_decoupler.tsv"
  - dc_pvals:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:‘test’, single_end ]
      - progeny_mlm_pvals_decoupler.tsv:
          type: file
          description: |
            The file containing the p-value associated to the estimation
            results of the enrichment(s)
          pattern: "progeny_mlm_pvals_decoupler.tsv"
  - dc_acts:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:‘test’, single_end ]
      - acts_decoupler.tsv:
          type: file
          description: |
            Activities in TSV format from the AnnData object
          pattern: "acts_decoupler.tsv"
  - dc_umap:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:‘test’, single_end ]
      - figures/*umap.png:
          type: file
          description: |
            UMAP plot
          pattern: "figures/*umap.png"
  - dc_violin:
      - meta:
          type: map
          description: |
            Violin plot
      - figures/*violin.png:
          type: file
          pattern: "figures/*violin.png"
  - dc_matrixplot:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:‘test’, single_end ]
      - matrixplot_decoupler.png:
          type: file
          description: |
            Matrix plot with dendrogram
          pattern: "matrixplot_decoupler.png"
  - versions:
      - versions.yml:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:‘test’, single_end ]
          pattern: "versions.yml"
authors:
  - "@atrigila"
